services:
  - type: web
    name: cs-explorer
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
