services:
  - type: web
    name: cs-explorer
    env: node
    region: ohio
    plan: free
    buildCommand: |
      cd backend
      npm ci --production
      npm rebuild sqlite3
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: true
